from sqlmodel import SQLModel, Field
from typing import Optional
from enum import Enum
from datetime import datetime

class TaskStatus(str, Enum):
    TODO = "Todos"
    IN_PROGRESS = "In Progress"
    DONE = "Done"
    FOR_TESTING = "For Testing"
    DEPLOYMENT = "Deployment"

class User(SQLModel, table=True):
    """
    Represents a user in the system.
    Corresponds to the 'user' database table.
    """
    id: Optional[int] = Field(default=None, primary_key=True, description="Unique identifier for the user.")
    username: str = Field(index=True, unique=True, description="Unique username for login.")
    email: str = Field(description="Email address of the user.")

class TaskBase(SQLModel):
    """
    Base attributes shared by all Task models (database and Pydantic schemas).
    """
    title: str = Field(description="Title of the task.")
    description: Optional[str] = Field(default=None, description="Detailed description of the task.")
    status: TaskStatus = Field(default=TaskStatus.TODO, description="Current status of the task.")

class Task(TaskBase, table=True):
    """
    Database table definition for 'task'.
    Inherits base attributes from TaskBase.
    """
    id: Optional[int] = Field(default=None, primary_key=True, description="Unique identifier for the task.")
    assignee_id: Optional[int] = Field(default=None, foreign_key="user.id", description="ID of the user assigned to this task.")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the task was created.")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the task was last updated.")

class TaskCreate(TaskBase):
    """
    Schema for creating a new task.
    Inherits all base fields.
    """
    pass

class TaskRead(TaskBase):
    """
    Schema for reading a task (returning to client).
    Includes the ID, which is generated by the DB.
    """
    id: int = Field(description="Unique identifier for the task.")
    assignee_id: Optional[int] = Field(default=None, description="ID of the user assigned to this task.")
    created_at: datetime = Field(description="Timestamp when the task was created.")
    updated_at: datetime = Field(description="Timestamp when the task was last updated.")

class TaskUpdate(SQLModel):
    """
    Schema for updating an existing task.
    All fields are optional because a user might update only one field.
    """
    title: Optional[str] = Field(default=None, description="New title for the task.")
    description: Optional[str] = Field(default=None, description="New detailed description for the task.")
    status: Optional[TaskStatus] = Field(default=None, description="New status for the task.")
    assignee_id: Optional[int] = Field(default=None, description="New assignee ID for the task.")
